### ISSUE TITLE
Compilation error: Not enough arguments for method apply.

### ISSUE THREAD

**Issue by livtanong** [by-implication/Badger#3]
This is even after ./resetdb.
! @6gk7coh10 - Internal server error, for (GET) [/] ->

play.PlayExceptions$CompilationException: Compilation error[not enough arguments for method apply: (name: String, constraint: String, encodeable: Boolean)play.core.DynamicPart in object DynamicPart.
Unspecified value parameter encodeable.]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14$$anonfun$apply$16.apply(PlayReloader.scala:304) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:304) ~[na:na]
    at play.PlayReloader$$anon$1$$anonfun$reload$2$$anonfun$apply$14.apply(PlayReloader.scala:298) ~[na:na]
    at scala.Option.map(Option.scala:145) ~[scala-library.jar:na]
[warn] play - No application found at invoker init

**Comment by livtanong** [comment]
Sobrang weird. When I modified conf/routes, and made controllers.Assets.at have a third parameter 'true', it suddenly complained about having TOO many parameters. When I removed it again, suddenly it works. tang ina naman o. I'm keeping this open for you to close if you don't think this'll happen again.
